zscaler/terraform-provider-zpa

zpa/resource_zpa_service_edge_group.go

Added `ValidateStringFloatBetween` custom function to `service_edge_group`

Added `ValidateStringFloatBetween` custom function to `service_edge_group`

---

zpa/resource_zpa_app_connector_group.go
zpa/resource_zpa_provisioning_key.go
zpa/resource_zpa_segment_group.go

Added string validation to `tcp_keep_alive_enabled` :wrench:

Added string validation to `tcp_keep_alive_enabled` :wrench:

---

GNUmakefile

:bug: Added `go mod vendor` && `go mod tidy` to `GNUMakefile`

:bug: Added `go mod vendor` && `go mod tidy` to `GNUMakefile`

---

examples/zpa_enrollment_cert/datasource.tf
examples/zpa_policy_access_rule/README.md
examples/zpa_policy_access_rule/main.tf
examples/zpa_policy_access_rule/zpa_policy_set_rule_CrowdStrike.tf
examples/zpa_policy_forwarding_rule/README.md
examples/zpa_policy_forwarding_rule/main.tf
examples/zpa_policy_set_rule_crwd_pre_zta_scim/README.md
examples/zpa_policy_set_rule_trusted_network/zpa_policy_set_rule_trusted_network.tf
examples/zpa_policy_timeout_rule/main.tf
examples/zpa_policy_type/datasource.tf
examples/zpa_posture_profile/main.tf
examples/zpa_server_group/main.tf
examples/zpa_trusted_network/datasource.tf

Updated and added examples for new datasources and resources

Updated and added examples for new datasources and resources

---

CHANGELOG.md
gozscaler/browseraccess/zpa_browser_access.go
zpa/common.go
zpa/data_source_zpa_browser_access.go
zpa/resource_zpa_app_server_controller.go
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_segment_group.go
zpa/resource_zpa_server_group.go
zpa/resource_zpa_service_edge_group.go

Added stateFunc to allow resource import via name and/or id :rocket:

Added stateFunc to allow resource import via name and/or id :rocket:

---

zpa/data_source_zpa_lss_config_controller.go
zpa/provider.go

Fixed ``data_source_lss_config_controller``[INFO] and [Error] message

Fixed ``data_source_lss_config_controller``[INFO] and [Error] message

---

gozscaler/provisioningkey/zpa_provisioning_key.go
zpa/resource_zpa_provisioning_key.go

Feat: import provissioning key by name or ID with or without specifying the association type

---

CHANGELOG.md
gozscaler/lssconfigcontroller/zpa_lss_config_controller.go
zpa/resource_zpa_browser_access.go
zpa/resource_zpa_lss_config_controller.go

Feature: Added support to import ``browser_access`` and ``lss_controller`` resources

Feature: Added support to import ``browser_access`` and ``lss_controller`` resources

---

zpa/resource_zpa_policy_access_rule.go

Reverts willguibr/terraform-provider-zpa#78

Revert "Accelerate zpa_policy_access_rule resource"

---

zpa/common/resourcetype/resource_type.go
zpa/common/testing/variable/variable.go
zpa/data_source_zpa_browser_access_test.go
zpa/resource_zpa_browser_access_test.go

ZPA-59: Refactored zpa-browser-access acctest

ZPA-59: Refactored zpa-browser-access acctest

---

vendor/modules.txt
zpa/common/resourcetype/resource_type.go
zpa/common/testing/variable/variable.go
zpa/data_source_zpa_lss_config_controller_test.go
zpa/resource_zpa_lss_config_controller_test.go

Refactored LSS Config Controller Tests

Refactored LSS Config Controller Tests

---

CHANGELOG.md
vendor/modules.txt
zpa/common.go
zpa/resource_zpa_application_segment.go
zpa/utils.go

zpa#65: Fix app_segment tcp/udp port_ranges update/replacement

zpa#65: Fix app_segment tcp/udp port_ranges update/replacement

---

.github/workflows/ci.yml
zpa/common.go
zpa/resource_zpa_app_connector_group.go
zpa/resource_zpa_app_server_controller.go
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_browser_access.go
zpa/resource_zpa_lss_config_controller.go
zpa/resource_zpa_provisioning_key.go
zpa/resource_zpa_segment_group.go
zpa/resource_zpa_server_group.go
zpa/resource_zpa_service_edge_group.go

Fix: Update golangci-linter

---

docs/data-sources/zpa_app_connector_controller.md
docs/resources/zpa_app_connector_group.md
docs/resources/zpa_application_segment.md
docs/resources/zpa_application_server.md
docs/resources/zpa_browser_access.md
docs/resources/zpa_policy_access_forwarding_rule.md
docs/resources/zpa_policy_access_rule.md
docs/resources/zpa_policy_access_rule_browser_access.md
docs/resources/zpa_policy_access_timeout_rule.md
docs/resources/zpa_provisioning_key.md
docs/resources/zpa_segment_group.md
docs/resources/zpa_server_group.md
docs/resources/zpa_service_edge_group.md

Fix: Update documentation

---

CHANGELOG.md
GNUmakefile
zpa/resource_zpa_app_server_controller.go
zpa/resource_zpa_application_segment.go

Fix: Application Server Controller upstream update

Fix: Application Server Controller upstream update

---

CHANGELOG.md
GNUmakefile
docs/data-sources/zpa_application_segment.md
docs/resources/zpa_application_segment.md
gozscaler/applicationsegment/zpa_application_segment.go
zpa/data_source_zpa_application_segment.go
zpa/resource_zpa_application_segment.go

New: Application Segment Parameter ``select_connector_close_to_app``

New: Application Segment Parameter ``select_connector_close_to_app``

---

GNUmakefile
gozscaler/config.go
zpa/provider.go

Fixed authentication mechanism to other zpa clouds

Fixed authentication mechanism to other zpa clouds

---

CHANGELOG.md
GNUmakefile
docs/data-sources/zpa_application_segment.md
docs/guides/release-notes.md
docs/resources/zpa_application_segment.md
gozscaler/appconnectorgroup/zpa_app_connector_group.go
gozscaler/config.go
zpa/provider.go
zpa/resource_zpa_app_connector_group.go

Fix: Documentation and Examples

Fix: Documentation and Examples

---

GNUmakefile
gozscaler/client/client.go
gozscaler/config.go
zpa/config.go
zpa/provider.go

Added Terraform userAgent for backend API tracking

Added Terraform userAgent for backend API tracking

---

CHANGELOG.md
GNUmakefile
zpa/common.go
zpa/resource_zpa_policy_access_forwarding_rule.go
zpa/resource_zpa_policy_access_inspection_rule.go
zpa/resource_zpa_policy_access_rule.go
zpa/resource_zpa_policy_access_timeout_rule.go

FIX: Policy configuration drift detection

FIX: Policy configuration drift detection

---

CHANGELOG.md
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_pra.go
zpa/utils.go

tcp/udp port fix for zpa_application_segment_pra

tcp/udp port fix for zpa_application_segment_pra

---

go.mod
go.sum

Updated to zscaler-sdk-go v0.1.1

Updated to zscaler-sdk-go v0.1.1

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_pra.go

Added tcp/udp port overlap validation to PRA resource

Added tcp/udp port overlap validation to PRA resource

---

zpa/resource_zpa_application_segment_inspection.go

Added tcp/udp port overlap validation to Inspection resource

Added tcp/udp port overlap validation to Inspection resource

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/resource_zpa_app_connector_group.go
zpa/resource_zpa_app_server_controller.go
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_pra.go
zpa/resource_zpa_inspection_custom_controls.go
zpa/resource_zpa_inspection_profile.go
zpa/resource_zpa_lss_config_controller.go
zpa/resource_zpa_policy_access_forwarding_rule.go
zpa/resource_zpa_policy_access_inspection_rule.go
zpa/resource_zpa_policy_access_rule.go
zpa/resource_zpa_policy_access_timeout_rule.go
zpa/resource_zpa_provisioning_key.go
zpa/resource_zpa_segment_group.go
zpa/resource_zpa_server_group.go
zpa/resource_zpa_service_edge_group.go

This PR allows TF to re-create the resource when TF state resource's remote counterpart is deleted.

re-create resources when remote resource is deleted

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/common.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_policy_access_timeout_rule.go

Added ForceNew to Timeout Policy reauth_idle

Added ForceNew to Timeout Policy reauth_idle

---

GNUmakefile
go.mod
go.sum

Add zscaler-sdk-go 0.4.1 to address pagination issue

Add sdk-go 0.4.1 to address pagination issue

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/resource_zpa_app_connector_group.go
zpa/resource_zpa_service_edge_group.go
zpa/utils.go

Added function to validate app connector group coordinates

Fix: App Connector Group Validate Coordinates

---

CHANGELOG.md
GNUmakefile
docs/data-sources/zpa_inspection_all_predefined_controls.md
docs/data-sources/zpa_inspection_custom_control.md
docs/data-sources/zpa_inspection_predefined_controls.md
docs/data-sources/zpa_inspection_profile.md
docs/resources/zpa_inspection_custom_control.md
docs/resources/zpa_inspection_profile.md
go.mod
go.sum
zpa/data_source_zpa_inspection_all_predefined_controls.go
zpa/data_source_zpa_inspection_custom_controls.go
zpa/data_source_zpa_inspection_custom_controls_test.go
zpa/data_source_zpa_inspection_predefined_controls.go
zpa/data_source_zpa_inspection_profile.go
zpa/data_source_zpa_inspection_profile_test.go
zpa/resource_zpa_inspection_custom_controls.go
zpa/resource_zpa_inspection_custom_controls_test.go
zpa/resource_zpa_inspection_profile.go
zpa/resource_zpa_inspection_profile_test.go
zpa/resource_zpa_policy_access_inspection_rule_test.go

Added New ZPA Inspection Control Parameters

Added New ZPA Inspection Control Parameters

---

CHANGELOG.md
GNUmakefile
docs/data-sources/zpa_lss_config_log_type_formats.md
docs/guides/release-notes.md
docs/resources/zpa_lss_config_controller.md
zpa/data_source_zpa_lss_config_log_types_formats.go
zpa/data_source_zpa_lss_config_log_types_formats_test.go
zpa/resource_zpa_lss_config_controller.go

feat: Added new LSS log_type attribute

feat: Added new LSS log_type attribute

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/data_source_zpa_app_connector_group.go
zpa/resource_zpa_server_group.go

(fix) server group server list attribute

(fix) server group server list attribute

---

GNUmakefile
zpa/resource_zpa_server_group.go

Fix server list in server groups

Fix server list in server groups

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
docs/resources/zpa_policy_access_rule.md
zpa/resource_zpa_policy_access_rule.go

(feat): Add REQUIRE_APPROVAL action to access rule

(feat): Add REQUIRE_APPROVAL action to access rule

---

CHANGELOG.md
GNUmakefile
docs/data-sources/zpa_app_connector_group.md
docs/data-sources/zpa_application_segment.md
docs/data-sources/zpa_application_segment_browser_access.md
docs/data-sources/zpa_application_segment_inspection.md
docs/data-sources/zpa_application_segment_pra.md
docs/guides/release-notes.md
docs/resources/zpa_app_connector_group.md
docs/resources/zpa_application_segment.md
docs/resources/zpa_application_segment_browser_access.md
docs/resources/zpa_application_segment_inspection.md
docs/resources/zpa_application_segment_pra.md
go.mod
go.sum
zpa/data_source_zpa_application_segment.go
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_application_segment_browser_access_test.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_inspection_test.go
zpa/resource_zpa_application_segment_pra.go
zpa/resource_zpa_application_segment_pra_test.go
zpa/resource_zpa_application_segment_test.go

(feat) Added new app segments attributes

(feat) Added new app segments attributes

---

CHANGELOG.md
GNUmakefile
docs/data-sources/zpa_access_policy_client_types.md
docs/data-sources/zpa_access_policy_platforms.md
go.mod
go.sum
zpa/common.go
zpa/config.go
zpa/data_source_zpa_access_policy_client_types.go
zpa/data_source_zpa_access_policy_client_types_test.go
zpa/data_source_zpa_access_policy_platform.go
zpa/data_source_zpa_access_policy_platform_test.go
zpa/provider.go

(fix) Added platform and client type validation

(fix) Added platform and client type validation

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/data_source_zpa_saml_attribute.go
zpa/data_source_zpa_scim_group.go

(fix) SCIM Group Search Pagination Issue #260

(fix) SCIM Group Search Pagination Issue #260

---

GNUmakefile
go.mod
go.sum
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_pra.go

(feat) Allow Empty Server Group in App Segment

(feat) Allow Empty Server Group in App Segment

---

zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_pra.go
zpa/utils.go

Added validation to select_closest_app_connector

(Fix)Added validation to select_closest_app_connector

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/resource_zpa_application_segment_pra.go

(fix) zpa_application_segment_pra Drift Issues

(fix) zpa_application_segment_pra Drift Issues

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
docs/resources/zpa_policy_access_rule.md
zpa/common.go

(feat) Added new ZPA Client Type zapp_partner

(feat) Added new ZPA Client Type zapp_partner

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/resource_zpa_service_edge_group.go

(Fix) Fix Service Edge Group Trusted Networks

(Fix) Fix Service Edge Group Trusted Networks

---

GNUmakefile
zpa/resource_zpa_application_segment.go

(fix) Service Edge Group Fix

---

CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
zpa/common.go

improve scim values searching

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
docs/resources/zpa_application_segment.md
docs/resources/zpa_application_segment_browser_access.md
docs/resources/zpa_application_segment_inspection.md
docs/resources/zpa_application_segment_pra.md
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_pra.go

(Fix) connector_close_to_app to all app segments

(Fix) connector_close_to_app to all app segments

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/resource_zpa_policy_access_forwarding_rule.go

(fix) Fix policy_forwarding_rule to ensure updates

(fix) Fix policy_forwarding_rule to ensure updates

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/resource_zpa_policy_access_inspection_rule.go
zpa/resource_zpa_policy_access_isolation_rule.go

(fix) Fix all access policies to ensure updates

(fix) Fix all access policies to ensure updates

---

CHANGELOG.md
docs/guides/release-notes.md
docs/index.md

(Doc) Updated documentation to v 2.7.7

(Doc) Updated documentation to v 2.7.7

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/data_source_zpa_service_edge.go
zpa/data_source_zpa_service_edge_group.go
zpa/resource_zpa_segment_group.go
zpa/resource_zpa_service_edge_group.go

(Fix) Fix ZPA Service Edge resource and datasource

(Fix) Fix ZPA Service Edge resource and datasource

---

CHANGELOG.md
docs/data-sources/zpa_app_connector_group.md
docs/data-sources/zpa_application_segment.md
docs/data-sources/zpa_application_segment_browser_access.md
docs/data-sources/zpa_application_server.md
docs/data-sources/zpa_provisioning_key.md
docs/data-sources/zpa_segment_group.md
docs/data-sources/zpa_server_group.md
docs/guides/release-notes.md
docs/index.md
docs/resources/zpa_app_connector_group.md
docs/resources/zpa_application_segment.md
docs/resources/zpa_application_segment_browser_access.md
docs/resources/zpa_application_server.md
docs/resources/zpa_provisioning_key.md
docs/resources/zpa_segment_group.md
docs/resources/zpa_server_group.md

(doc): Updated documentation with new video links

(doc): Updated documentation with new video links

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
zpa/resource_zpa_policy_access_rule_test.go
zpa/resource_zpa_server_group.go

Fix: Server Group panic issue

---

.github/workflows/ci.yml
CHANGELOG.md
docs/guides/release-notes.md
zpa/data_source_zpa_lss_config_log_types_formats_test.go
zpa/provider.go

feat: Added support to ZPA QA environment

feat: Added support to ZPA QA environment

---

.github/workflows/ci.yml
.github/workflows/reuse-zpa-tests.yml
.github/workflows/test.yml
GNUmakefile
zpa/data_source_zpa_application_segment_browser_access_test.go
zpa/resource_zpa_application_segment_browser_access_test.go

feat: Refactor CICD workflow

---

docs/data-sources/zpa_application_segment.md
docs/resources/zpa_application_segment.md

(doc) Documentation update with new attributes

(doc) Documentation update with new attributes

---

GNUmakefile
zpa/resource_zpa_policy_access_forwarding_rule.go
zpa/resource_zpa_policy_access_rule.go

Fix: Remove policy rule order validation

Fix: Remove policy rule order validation

---

zpa/common.go
zpa/resource_zpa_policy_access_rule_reorder.go
zpa/resource_zpa_policy_access_rule_reorder_test.go

fix: Added check to prevent unecessary reorder

fix: Added check to prevent unecessary reorder

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/resource_zpa_policy_access_rule_reorder.go
zpa/resource_zpa_policy_access_rule_reorder_test.go

fix: Removed replacedByRule condition in ruleOrder

fix: Removed replacedByRule condition in ruleOrder

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/common.go

fix: Access Policy Condition Updates

fix: Access Policy Condition Updates

---

GNUmakefile
docs/guides/troubleshooting.md
docs/index.md
scripts/upgrade-namespace.py
tools.go
zpa/provider.go
zpa/resource_zpa_policy_access_rule_reorder_test.go

1. Added troubleshooting document
2. Updated Index credential content
3. Updated GNUMakefile with gofmt and others.

(Doc) Updated Documentation

---

zpa/data_source_zpa_application_segment_inspection_test.go
zpa/resource_zpa_application_segment_inspection_test.go
zpa/resource_zpa_application_segment_pra_test.go

Fix: Fixed Application segment inspection domain random string

Fix: Fixed Application segment inspection domain random string

---

.github/workflows/reuse-zpa-tests.yml

(gh-action): Implement retry workflow method

(gh-action): Implement retry workflow method

---

.github/workflows/reuse-zpa-tests.yml
.github/workflows/test.yml
GNUmakefile
go.mod
zpa/data_source_zpa_application_segment_pra_test.go
zpa/provider_sweeper_test.go
zpa/provider_test.go
zpa/resource_zpa_app_connector_group_test.go
zpa/resource_zpa_app_server_controller_test.go
zpa/resource_zpa_application_segment_pra_test.go
zpa/resource_zpa_inspection_profile_test.go
zpa/resource_zpa_lss_config_controller_test.go
zpa/resource_zpa_policy_access_forwarding_rule_test.go
zpa/resource_zpa_policy_access_inspection_rule_test.go
zpa/resource_zpa_policy_access_isolation_rule.go
zpa/resource_zpa_policy_access_isolation_rule_test.go
zpa/resource_zpa_policy_access_rule_test.go
zpa/resource_zpa_policy_access_timeout_rule_test.go
zpa/resource_zpa_segment_group_test.go
zpa/resource_zpa_service_edge_group_test.go
zpa/utils_for_test.go

Implemented sweeper test for cleanup

Implemented sweeper test for cleanup

---

docs/data-sources/zpa_app_connector_controller.md
examples/zpa_policy_access_rule_reorder/README.md
examples/zpa_policy_access_rule_reorder/advanced.tf
examples/zpa_policy_access_rule_reorder/basic.tf

(doc): Added rule_order resource example

(doc): Added rule_order resource example

---

CHANGELOG.md
docs/guides/release-notes.md
docs/guides/troubleshooting.md
docs/resources/zpa_policy_access_rule.md
go.mod
go.sum
zpa/common.go
zpa/resource_zpa_policy_access_forwarding_rule.go
zpa/resource_zpa_policy_access_inspection_rule.go
zpa/resource_zpa_policy_access_isolation_rule.go
zpa/resource_zpa_policy_access_rule.go
zpa/resource_zpa_policy_access_timeout_rule.go
zpa/utils.go

feat: Added country code objectType support and validation

feat: Added country code objectType support and validation

---

docs/resources/zpa_policy_access_forwarding_rule.md
docs/resources/zpa_policy_access_inspection_rule.md
docs/resources/zpa_policy_access_isolation_rule.md
docs/resources/zpa_policy_access_rule.md
docs/resources/zpa_policy_access_rule_application_segment.md
docs/resources/zpa_policy_access_rule_browser_access.md
docs/resources/zpa_policy_access_rule_posture_profile.md
docs/resources/zpa_policy_access_rule_saml.md
docs/resources/zpa_policy_access_rule_scim_attribute.md
docs/resources/zpa_policy_access_rule_scim_group.md
docs/resources/zpa_policy_access_rule_trusted_networks.md
docs/resources/zpa_policy_access_timeout_rule.md

(doc) Updated access policy documentation

(doc) Updated access policy documentation

---

CHANGELOG.md
GNUmakefile
docs/guides/resource-importer.md
docs/guides/support.md
docs/index.md
examples/zpa_cloud_browser_isolation_certificate/README.md
examples/zpa_cloud_browser_isolation_external_profile/README.md
examples/zpa_cloud_browser_isolation_region/README.md
examples/zpa_cloud_browser_isolation_region/datasource.tf
examples/zpa_cloud_browser_isolation_zpa_profile/README.md
examples/zpa_cloud_browser_isolation_zpa_profile/datasource.tf
examples/zpa_isolation_profile/README.md
examples/zpa_isolation_profile/datasource.tf
examples/zpa_microtenant_controller/README.md
examples/zpa_policy_type/datasource.tf
go.mod
go.sum
zpa/data_source_zpa_cloud_browser_isolation_external_profile_test.go
zpa/data_source_zpa_lss_config_controller_test.go
zpa/provider_sweeper_test.go
zpa/provider_test.go
zpa/resource_zpa_cloud_browser_isolation_external_profile_test.go
zpa/resource_zpa_lss_config_controller_test.go

feat: Release v3.0.0-beta

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
main.go
zpa/common/version.go
zpa/provider.go
zpa/provider_sweeper_test.go
zpa/provider_test.go

(Fix): Added enhanced user-agent header information
i.e
``User-Agent: (darwin arm64) Terraform/1.5.5 Provider/3.0.2 CustomerID/xxxxxxxxxxxxxxx``

(Fix): Added enhanced user-agent header information

---

.github/workflows/test.yml
CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
docs/resources/zpa_application_segment_inspection.md
go.mod
go.sum
zpa/data_source_zpa_machine_group_test.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_pra.go

(fix): Fixed application segment pra and inspection

(fix): Fixed application segment pra and inspection

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/provider.go
zpa/version.go

(Fix) Fixed authentication method via provider block

(Fix) Fixed authentication method via provider block

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
examples/zpa_lss_config_controller/lss_config_application_segment.tf
examples/zpa_lss_config_controller/lss_config_log_type_user_activity.tf
examples/zpa_lss_config_controller/lss_config_log_type_user_status.tf
examples/zpa_lss_config_controller/lss_config_segment_group.tf
go.mod
go.sum
zpa/data_source_zpa_enrollement_cert.go
zpa/resource_zpa_policy_access_forwarding_rule.go
zpa/resource_zpa_policy_access_inspection_rule.go
zpa/resource_zpa_policy_access_isolation_rule.go
zpa/resource_zpa_policy_access_rule.go
zpa/resource_zpa_policy_access_timeout_rule.go

(fix): Fixed Microtenant ID attribute for access policies

(fix): Fixed Microtenant ID attribute for access policies

---

.github/workflows/reuse-zpa-tests.yml
.github/workflows/test.yml
CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/version.go

feat: Implemented SCIM Group SortOrder and SortBy Options

feat: Implemented SCIM Group SortOrder and SortBy Options

---

.github/workflows/test.yml
CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/resource_zpa_provisioning_key.go
zpa/version.go

(fix): Removed  computed attribute from provisioning key

(fix): 🔧 Removed  computed attribute from provisioning key

---

CHANGELOG.md
docs/data-sources/zpa_app_connector_assistant_schedule.md
docs/guides/release-notes.md
docs/resources/zpa_app_connector_assistant_schedule.md
examples/zpa_app_connector_assistant_schedule/basic.tf
examples/zpa_app_connector_assistant_schedule/datasource.tf
examples/zpa_policy_access_rule/main.tf
go.mod
go.sum
zpa/common/version.go
zpa/data_source_zpa_app_connector_assistant_schedule.go
zpa/data_source_zpa_app_connector_assistant_schedule_test.go
zpa/provider.go
zpa/resource_zpa_app_connector_assistant_schedule.go
zpa/resource_zpa_app_connector_assistant_schedule_test.go

(feat): Added App Connector Assistant Schedule datasource and resource

(feat): Added App Connector Assistant Schedule datasource and resource

---

.github/workflows/zpa-test.yml
CHANGELOG.md
GNUmakefile
docs/resources/zpa_policy_redirection_rule.md
go.mod
go.sum
zpa/common.go
zpa/common/version.go
zpa/data_source_zpa_application_segment_by_type_test.go
zpa/data_source_zpa_inspection_profile_test.go
zpa/provider_sweeper_test.go
zpa/provider_test.go
zpa/resource_zpa_application_segment_pra_test.go
zpa/resource_zpa_inspection_profile_test.go
zpa/resource_zpa_policy_access_inspection_rule_test.go
zpa/resource_zpa_policy_access_inspection_rule_v2.go
zpa/resource_zpa_policy_access_inspection_rule_v2_test.go
zpa/resource_zpa_policy_credential_access_rule_test.go
zpa/resource_zpa_pra_approval_test.go
zpa/resource_zpa_pra_console_controller.go
zpa/resource_zpa_pra_console_controller_test.go
zpa/resource_zpa_pra_credential_controller.go
zpa/utils.go
zpa/version.go

Fix: Fixed drifts and CodeQL warnings

Fix: Fixed drifts and CodeQL warnings

---

.github/pull_request_template.md
.github/workflows/zpa-test.yml
CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
examples/zpa_policy_credential_rule/basic.tf
examples/zpa_service_edge_assistant_schedule/basic.tf
examples/zpa_service_edge_assistant_schedule/datasource.tf
zpa/common.go
zpa/data_source_zpa_application_segment_browser_access.go
zpa/data_source_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_pra.go
zpa/resource_zpa_policy_access_forwarding_rule_v2_test.go

fix: Fixed missing/needed attributes from application segments

fix: Fixed missing/needed attributes from application segments

---

CHANGELOG.md
GNUmakefile
docs/data-sources/zpa_microtenant_controller.md
docs/guides/release-notes.md
docs/resources/zpa_microtenant_controller.md
zpa/data_source_zpa_cloud_browser_isolation_external_profile_test.go
zpa/data_source_zpa_microtenant_controller.go
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_cloud_browser_isolation_external_profile_test.go
zpa/resource_zpa_microtenant_controller.go
zpa/resource_zpa_service_edge_group.go

Fix: Fixed Application Segment Drift and Microtenant missing attribute

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/common.go
zpa/resource_zpa_policy_access_forwarding_rule.go
zpa/resource_zpa_policy_access_inspection_rule.go
zpa/resource_zpa_policy_access_isolation_rule.go
zpa/resource_zpa_policy_access_rule_v2.go
zpa/resource_zpa_provisioning_key.go
zpa/resource_zpa_segment_group.go

feat: Added support to segment group v2 API and Fixes

---

CHANGELOG.md
docs/guides/release-notes.md
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_application_segment_pra.go

fix: Application Segment Microtenant ID drift

---

.github/workflows/zpa-test.yml
CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/common.go
zpa/data_source_zpa_application_segment_by_type_test.go
zpa/resource_zpa_policy_access_forwarding_rule_v2.go
zpa/resource_zpa_policy_access_inspection_rule_v2.go
zpa/resource_zpa_policy_access_isolation_rule_v2.go
zpa/resource_zpa_policy_access_rule_v2.go
zpa/resource_zpa_policy_access_timeout_rule_v2.go
zpa/resource_zpa_policy_capabilities_access_rule.go
zpa/resource_zpa_policy_capabilities_access_rule_test.go
zpa/resource_zpa_policy_credential_access_rule.go
zpa/resource_zpa_segment_group_test.go

fix: Fixed Policy Access v2 Drift

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/data_source_zpa_application_segment_by_type_test.go
zpa/data_source_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_inspection_test.go
zpa/resource_zpa_application_segment_pra.go
zpa/resource_zpa_application_segment_pra_test.go
zpa/resource_zpa_segment_group.go

fix: Fixed PRA and Inspection Application Segment drifts

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/resource_zpa_application_segment.go

fix: Fixed issue with application segment tcp_port_range and udp_port_range

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
zpa/common.go
zpa/resource_zpa_policy_access_rule.go
zpa/resource_zpa_policy_credential_access_rule_test.go
zpa/resource_zpa_pra_approval_test.go
zpa/resource_zpa_pra_console_controller_test.go

fix: Fixed zpa_policy_access_rule and semver issues

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum

fix: Upgraded to Zscaler SDK GO v3.1.9

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum

fix: Fixed URL Encoding Issue

---

CHANGELOG.md
docs/guides/release-notes.md
docs/resources/zpa_application_segment.md
docs/resources/zpa_application_segment_browser_access.md
docs/resources/zpa_application_segment_inspection.md
docs/resources/zpa_application_segment_pra.md
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_application_segment_inspection.go
zpa/resource_zpa_application_segment_pra.go

fix: Added fqdn_dns_check attribute to Application Segments

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
docs/index.md
docs/resources/zpa_application_segment_pra.md
zpa/common.go
zpa/resource_zpa_policy_access_rule_v2.go
zpa/resource_zpa_service_edge_group.go

fix: fixed Service Edge Group drifts and Application Segment attribute

---

CHANGELOG.md
docs/guides/release-notes.md
docs/resources/zpa_application_segment_pra.md
docs/resources/zpa_service_edge_group.md
zpa/common.go
zpa/resource_zpa_policy_access_redirection_rule.go
zpa/resource_zpa_policy_access_rule.go
zpa/resource_zpa_policy_access_rule_v2.go
zpa/resource_zpa_server_group.go
zpa/resource_zpa_server_group_test.go
zpa/resource_zpa_service_edge_group.go
zpa/resource_zpa_service_edge_group_test.go

Fixed `zpa_service_edge_group` drift with nested blocks.

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
docs/resources/zpa_service_edge_group.md
examples/zpa_service_edge_controller/datasource.tf
go.mod
go.sum
zpa/data_source_zpa_application_segment.go
zpa/resource_zpa_application_segment.go
zpa/resource_zpa_policy_access_timeout_rule_v2.go
zpa/resource_zpa_service_edge_group.go

fix: Included additional Policy Timeout and Service Edge Group Drift Checking

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
docs/resources/zpa_pra_portal_controller.md
go.mod
go.sum
zpa/resource_zpa_pra_portal_controller.go

fix: Added support for PRA User Portal with Zscaler Managed Certificate to resource `zpa_pra_portal_controller`

---

CHANGELOG.md
docs/data-sources/zpa_application_segment_browser_access.md
docs/guides/release-notes.md
docs/resources/zpa_application_segment_browser_access.md
docs/resources/zpa_pra_portal_controller.md
go.mod
go.sum
zpa/data_source_zpa_application_segment_browser_access.go
zpa/data_source_zpa_pra_portal_controller.go
zpa/resource_zpa_application_segment_browser_access.go
zpa/resource_zpa_pra_approval_test.go
zpa/resource_zpa_pra_portal_controller.go

fix: Added support for Zscaler Managed Certificate to resource

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
docs/resources/zpa_policy_browser_protection_rule.md
docs/resources/zpa_policy_capabilities_rule.md
docs/resources/zpa_policy_credential_rule.md
docs/resources/zpa_policy_forwarding_rule_v2.md
docs/resources/zpa_policy_inspection_rule_v2.md
docs/resources/zpa_policy_isolation_rule_v2.md
docs/resources/zpa_policy_timeout_rule_v2.md
zpa/common.go
zpa/provider.go
zpa/resource_zpa_policy_access_browser_protection_rule_v2.go

feat: Added new Browser Protection Rule Policy Resource

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/resource_zpa_policy_access_rule_reorder.go
zpa/resource_zpa_policy_access_rule_v2.go

fix: Improved zpa_policy_access_rule_reorder to better handle Deception rule ordering

---

CHANGELOG.md
GNUmakefile
docs/guides/release-notes.md
go.mod
go.sum
zpa/resource_zpa_app_connector_group.go

fix: Fixed App Connector Group lss_app_connector_group
